Use Gym to train stats (#107) update
alainbryden/bitburner-scripts pull request #303
Opened 2023-05-31 12:23 UTC by Arthan-the-one

-should now respect focus settings
-calculates that training can finish before traveling to gym
--(including backdoor discount)
-code deduplication/refactoring
-only attempt to travel if in wrong city
-option no-gym to disable gym
-split gym logic from crime logic, crime first
-correct eta-calc on bitnodes with stat multipliers
-use best gym available with current money, including travel expenses

Already in the original MR:
-ETA for training
-logic for price calculation
-the training itself
-travel to city of best gym

ToDo:
-push karma to -52k if gangs are unlocked before using the gym - maybe make configurable/be intelligent about it, might take a lot of time
-consider adding option to limit training money

fixes #107

2023-05-31 14:43 UTC, alainbryden requested changes

2023-05-31 14:43 UTC, alainbryden commented on work-for-factions.js
>      ns.print(`Done committing crimes. Reached ${strRequirements.map(r => r()).join(', ')}`);
I think this is close to being the right approach, but it will generate quite a bit of confusion if the player ends up doing gym training for a while, and then logs "Done committing crimes".

I would take this abstraction a bit further:
 - rename `crimeForKillsKarmaStats` to something like `earnKillsKarmaOrStats`
 - wrap anything specific to crime in its own function `doCrime` (similar to your new `doGymTraining` function)
 - Fork the logic above based on whether we decided to to crime, and only log "Done committing crimes" if we went down that path. Similarily, generate an equivalent "Done gym training" if we went down that path.

2023-05-31 14:43 UTC, alainbryden commented on work-for-factions.js
> +    if ((player.money - travelCost) < gymCost) return ns.print(`Warn: You're too poor to finish training, get at least ${gymCost + travelCost} money`)
A couple questions / suggestions:
- If we cannot afford to travel to the gym of our choosing, should we not fall-back to whatever gym is in the current city, and only return a warning like this if there is no gym available?
- Similar to what is in sleeves.js, we need to detect if the player is traning into negative money, and prevent that from happening. There should probably be similar associated options (command line parameters) that limit training by money and/or by time.

2023-05-31 14:43 UTC, alainbryden commented on work-for-factions.js
> +            ns.singularity.gymWorkout(bestGym, stats[currentStat], shouldFocus)
Pretty sure we need to add ram-dodging for this and all other ns functions you use in this method to avoid increasing the RAM footprint of this script.

2023-05-31 14:43 UTC, alainbryden commented on work-for-factions.js
> +    while (forever || player.numPeopleKilled < reqKills || -ns.heart.break() < reqKarma) {
From the feature request: #107
It was suggested that if Gangs are unlocked, we should always prioritize "training" via crime (e.g. Karma generating actions) until we have the -52K karma required to join a gang, and only resort to gym-training after the gang.

Once we've abstracted this a bit more to have a clear upfront "decision" on whether to use crime or gym to train, we can add some logic to that decision-making process to favour crime if we're not yet in a gang. We can re-use the `options['no-crime']` check if ever someone wanted to override this and hit the gym instead.

That also raises a good point. Everything that calls this function is gated behind a `options['no-crime']` check, which will skip it - but now that this function might also be opting to use the gym, we will need to move that check from outside of the function to inside of it, and revise usages to make sure they make sense. We'll probably also want to add an equivalent `options['no-gym']` option for anyone wanting to similarily avoid working out.

2023-05-31 15:02 UTC, alainbryden commented
Thanks for doing the heavy lifting. There are some potential side-effects and "configurability" issues I would like addressed. If there's anything you want to tackle, feel free, otherwise I'm happy to "take over" at any point to polish off the bits I feel are missing.

2023-06-02 10:02 UTC, alainbryden commented on work-for-factions.js
> +    if ((player.money - travelCost) < gymCost) return ns.print(`Warn: You're too poor to finish training, get at least ${gymCost + travelCost} money`)
Scripts can't count on other scripts not spending money so it's great that you can check up front but you still do have to continuously monitor money and stop if it starts to get low.

2023-09-12 02:42 UTC, s0r3-glitch commented
I have been testing this over the past few days and have found that I have had a lot of problems when it comes to ascending. I keep getting errors about an unexpected money change right before buying everything for ascending causing the script to fail out and stop running completely. At one point  during 4.3 (i think) I had the issue of it trying to spend 860b on rep well i had something like 2t in raw cash. Now I am not 100% sure that this problem is entirely due to the code in this PR but i figured I would bring it up here since its the code.

2024-10-02 23:32 UTC, alainbryden commented
> I have been testing this over the past few days and have found that I have had a lot of problems when it comes to ascending. I keep getting errors about an unexpected money change right before buying everything for ascending causing the script to fail out and stop running completely. At one point during 4.3 (i think) I had the issue of it trying to spend 860b on rep well i had something like 2t in raw cash. Now I am not 100% sure that this problem is entirely due to the code in this PR but i figured I would bring it up here since its the code.

A year late, but I think this might be a separate issue #328 - but I appreciate you testing this PR.

2025-07-05 16:54 UTC, closed without merging